<!DOCTYPE html>

<html lang="en"> <!-- manifest="cache-manifest.php"> -->
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<title>timeTrack</title>

	<link href="style.css" media="screen" rel="stylesheet" type="text/css">
	<style type="text/css" media="screen">@import "jqtouch/jqtouch/jqtouch.min.css";</style>
	<style type="text/css" media="screen">@import "jqtouch/themes/jqt/theme.min.css";</style>

	<script src="jqtouch/jqtouch/jquery.1.3.2.min.js" type="text/javascript" charset="utf-8"></script>
	<script src="jqtouch/jqtouch/jqtouch.min.js" type="application/x-javascript" charset="utf-8"></script>

	<script type="text/javascript" src="mobile2.js"></script>
</head>
<body>
    <div id="home">
        <div class="toolbar">
            <h1>TimeTrack</h1>
			<?php if($loggedin) : ?>
            <a class="button slideup" href="#page2">Stats</a>
			<?php endif; ?>
        </div>

		<?php  if(isset($_POST['u']) && isset($_POST['p'])) : ?>
			<?php  if(!$loggedin) : ?>
				<ul class="edgetoedge" style="background-color: #c00;">
					<li style="color: #fff; text-align: center;">
						Logindaten nicht korrekt!
					</li>
				</ul>
			<?php else : ?>
				<div class="info">
					Foreverlink:
					<?php $link= 'http://'.$_SERVER['SERVER_NAME']. dirname($_SERVER['SCRIPT_NAME']) .'/?h=' . $hash; ?>
					<a href="<?php echo $link; ?>"><?php echo $link; ?></a>
				</div>
			<?php endif; ?>
		<?php endif; ?>

		<?php if(!$loggedin) : ?>
		        <form method="post" action="<?php echo $_SERVER['SCRIPT_NAME']; ?>">
		            <ul class="edit form">
		            	<li><input type="text" name="u" id="name" placeholder="Username" /></li>
		            	<li><input type="password" name="p" id="password" placeholder="Password" /></li>
		            </ul>
		           	<input type="submit" name="submit" style="margin: 10px auto; width: 90%" class="whiteButton"  value="Login" />
		        </form>

			</div>

		<?php else : ?>

			<form class="expressform" style="text-align: center; margin-bottom: 30px; padding-top: 40px;">
				<button name="d" value="" id="change_button">&nbsp;</button>
				<input type="hidden" name="h" value="<?php echo $hash; ?>">
			</form>

			<div class="metal" style="position: absolute; bottom: 0px; width: 100%;">
				<ul style="text-align: center;">
					<li>
						<?php
						echo 'am <span class="last_date">&bull;&bull;&bull;</span> um <span class="last_time">&bull;&bull;&bull;</span>';
						echo '<br><strong class="direction_action">&bull;&bull;&bull;</strong>';
						?>
					</li>
				</ul>
			</div>
		    </div>

			<div id="page2">
		        <div class="toolbar">
		            <h1>Stats</h1>
		            <a class="button back" href="#home">Home</a>
		            <a class="button slideup" href="#graphs">Graphs</a>
		        </div>

				<ul>
					<li style="color: #bbb;">
						<span class="diff_label">Ankunft:</span>
						<span id="stats_startstamp" style="float: right">
						</span>
					</li>
					<li style="color: #bbb;">
						<span class="diff_label">Pause:</span>
						<span id="stats_pause" style="float: right">
						</span>
					</li>
					<li style="color: #bbb;">
						<span class="diff_label">Feierabend:</span>
						<span id="stats_finishingtime" style="float: right">
						</span>
					</li>
					<li style="color: #bbb;">
						<span class="diff_label">Differenz:</span>
						<span id="stats_diff" style="float: right">
						</span>
					</li>
					<li style="color: #bbb;">
						<span class="monthdiff_label">Monatsbilanz:</span>
						<span id="stats_monthdiff" style="float: right">
						</span>
					</li>
				</ul>
			</div>

			<div id="graphs">
		        <div class="toolbar" id="graphtoolbar">
		            <h1>Graphs</h1>
		            <a class="button back" href="#home">Home</a>
		        </div>

			</div>

		<?php endif; ?>

</body>
</html>
