<!DOCTYPE html>

<html lang="de">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<title>Zeittabelle - wann komme ich, wann gehe ich?</title>
	<meta name="author" content="">
	<link href="static/css/style.css" media="screen" rel="stylesheet" type="text/css">
	<link rel="shortcut icon" href="static/img/favicon.ico" />
	<link rel="icon" href="static/img/favicon.ico" type="image/ico" />
</head>
<body>

<div id="timeSlider">
	<div class="gutter">
		<div class="range"></div>
		<div class="startKnob"></div>
		<div class="endKnob"></div>
	</div>

	<div class="date">
		<span class="startDate"></span> -
		<span class="endDate"></span>
	</div>

</div>

<form id="form_correction" action="correct.php" method="post">
	<input type="hidden" id="form_oldstart" name="oldstart" value="<?php echo $day['startstamp'] ?>">
	<input type="hidden" id="form_oldend" name="oldend" value="<?php echo $day['endstamp'] ?>">
	<input type="hidden" id="form_newstart" name="newstart" value="<?php echo $day['startstamp'] ?>">
	<input type="hidden" id="form_newend" name="newend" value="<?php echo $day['endstamp'] ?>">
	<input type="hidden" id="form_date" name="date" value="<?php echo $curdate ?>">
	<input type="submit" name="submit" value="Aktualisieren">
</form>

<div style="margin-top: 15px;" id="change_dailyworktime">
	<?php $halfday = ($day['dailyWorkTime'] == 4.41666); ?>
	<form id="form_dailyworktime"  action="correct.php" method="post">
		<?php if($halfday) : ?>
			Halber Arbeitstag (4:25h)
			<input type="submit" name="submit" value="Als vollen Tag berechnen (8:45h)">
			<input type="hidden" name="daysize" value="wholeday">
		<?php else: ?>
			Voller Arbeitstag (8:45h)
			<input type="submit" name="submit" value="Als halben Tag berechnen (4:25h)">
			<input type="hidden" name="daysize" value="halfday">
		<?php endif; ?>
		<input type="hidden" name="date" value="<?php echo $curdate ?>">
	</form>
</div>

<script type="text/javascript">
	var starttimestamp = <?php echo $day['startstamp'] ?>;
	var endtimestamp = <?php echo $day['endstamp'] ?>;
	var date = "<?php echo $day['date'] ?>".split(/-/);
</script>

<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/mootools/1.4/mootools-yui-compressed.js"></script>
<script type="text/javascript" src="static/js/mootools-1.4.0.1-more.js"></script>
<script type="text/javascript" src="static/js/TimeSlider.js"></script>
<?php if(isset($_SERVER['HTTP_X_REQUESTED_WITH']) && $_SERVER['HTTP_X_REQUESTED_WITH'] == 'XMLHttpRequest') : ?>
	<script type="text/javascript">
	<?php readfile("static/js/correct.js") ?>
	</script>
<?php else: ?>
	<script type="text/javascript" src="static/js/correct.js"></script>
<?php endif; ?>

</body>
</html>
