<!DOCTYPE html>

<html lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<title>Daemon downloaden</title>
	<title>Zeittabelle - Daemon downloaden</title>
	<meta name="author" content="">
	<link href="static/css/style.css" media="screen" rel="stylesheet" type="text/css">
	<link rel="shortcut icon" href="static/img/favicon.ico" />
	<link rel="icon" href="static/img/favicon.ico" type="image/ico" />
	
</head>
<body>
<h1>Daemon herunterladen</h1>
<p>
	Der daemon ist fertig konfiguriert und muss nur so installiert werden, dass er beim Starten
	des Systems immer läuft!
</p>
	<a href="<?php echo $_SERVER['REQUEST_URI'] ?>&d=y">Download</a>
</body>
</html>

