<!DOCTYPE html>

<html lang="de">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<title>TimeTrack</title>
	<link href="static/css/style.css" rel="stylesheet" type="text/css">		
	<?php if($this->mobiledevice) : ?>
		<meta name="viewport" content="width=320; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;"/>
		<link href="static/css/style.handheld.css" rel="stylesheet" type="text/css">		
		<meta name="apple-mobile-web-app-capable" content="yes">
		<link rel="apple-touch-icon" href="static/img/favicon.png">
		<link rel="apple-touch-startup-image" href="static/img/startupimage.png">
		<meta name="apple-mobile-web-app-status-bar-style" content="black">
	<?php endif; ?>
	<link rel="shortcut icon" href="static/img/favicon.ico" />
	<link rel="icon" href="static/img/favicon.ico" type="image/ico" />
</head>
<body>
