<?php if (isset($error)): ?>
<div id="error_box">
	<strong><?php echo $error ?></strong>
</div>
<?php endif; ?>
<form class="login" action="show.php" method="post">
	<h1>
	TimeTrack
	</h1>
	<p>
	<label for="name">Benutzername:</label><br>
		<input type="text" name="u" id="name" />
	</p><p>
	<label for="password">Passwort:</label><br>
		<input type="password" name="p" id="password" />
	</p>
	<p>
		<input type="submit" id="login" value="Login" />
	</p>
</form>
