<div id="month_navigator">

	<div id="action_menu">
		<ul>
		<li>
		<a href="#" id="changeuserdata_action_link">Logindaten</a>
		<div id="changeuserdata_widow" class="settings_popdown">
			<form action="<?php echo dirname($_SERVER["SCRIPT_NAME"]) ?>/action.php" method="POST" autocomplete="off">
				<input type="hidden" name="action"  value="changeuserdata">
				Username:<br>
				<?php if(isset($username)) : ?>
					<strong><?php echo $username; ?></strong>
					<input type="hidden"id="changeuserdata_user" name="changeuserdata_user"  value="<?php echo $username; ?>">
				<?php else : ?>
					<input type="text" id="changeuserdata_user" name="changeuserdata_user" value="">
				<?php endif; ?>
				<br>
				Passwort:<br>
				<input type="password" id="changeuserdata_pass" name="changeuserdata_pass">

				<input type="submit">
			</form>
		</div>
		</li>
<!--
		<li>
		<a href="#" id="correct_action_link">Korrigieren</a>
		<div id="correct_widow" class="settings_popdown">
			<form action="<?php echo $_SERVER["SCRIPT_NAME"] ?>" method="get">
			Korrektur in Minuten:
			<input type="text" id="correction_value" name="correction_value">
			Korrigierte Differenz:
			<input type="text" id="correction_absolute" name="correction_absolute">

			<input type="submit">
			</form>
		</div>
		</li>
		 -->
		<li>
			<a href="dropbox.php" id="dropBoxLink" rel="{handler:'iframe'}" style="height: 36px; width: 50px;">
				<div style="background: url(static/img/dropbox-backup.png) no-repeat center center; height: 36px;"></div>
			</a>
		</li>

		</ul>
	</div>

	<div id="additional_months" class="hidden">
		<ul>
			<?php foreach($this->data['months'] as $month=>$time): ?>
				<li>
					<a href="<?php echo $_SERVER["SCRIPT_NAME"] ?>?m=<?php echo $month ?>" class="<?php echo ($month==$this->curmonth ? 'active' : '') ?>"><?php echo formatmonth($month) ?></a>
				</li>
			<?php endforeach; ?>
		</ul>
	</div>

	<div id="months">
		<ul>
		<li>
			<a href="#" id="previous_months_link">Alle Monate</a>
		</li>
		<li>
			<a href="<?php echo $_SERVER["SCRIPT_NAME"] ?>?m=<?php echo $month ?>" class="<?php echo ($month==$this->curmonth ? 'active' : '') ?>"><?php echo formatmonth($month) ?></a>
		</li>
		</ul>
	</div>
	<div id="current_month"><?php echo formatmonth($this->curmonth); ?></div>

</div>

<?php if(count($this->data['days']) < 1) : ?>
	<div id="overview" style="text-align: center;">
		<p>Für diesen Monat liegen keine Daten vor.</p>
	</div>
<?php else: ?>
<div id="overview">
	<?php if ($this->curmonth==date('Ym') && count($this->day) > 0) : ?>
		<div class="day_data">
			<span class="diff_label">Ankunft:</span><br>
			<?php echo date("G:i:s", $this->day['startstamp']) ?>
		</div>

		<div class="day_data">
			<span class="diff_label">Pause:</span><br>
			<?php echo gmdate("G:i:s", $this->day['pause']) ?>
		</div>

		<div class="day_data">
			<span class="diff_label">Feierabend:</span><br>
			<?php echo date("G:i:s", $this->normalEnd) ?>
		</div>

	    <div id="day_diff_earliest" class="" style="height:48px;">
	    	<?php $countdownParam = http_build_query(array('std'=>date("G",$this->earliestEnd),'min'=>date("i",$this->earliestEnd),'sec'=>date("s",$this->earliestEnd)));?>
	    	<a href="#" onclick="javascript:window.open('countdown.php?<?php echo $countdownParam; ?>','countdownwindow','innerHeight=100px,innerWidth=300px,dependent=no,resizable=no,scrollbars=no,status=no,toolbar=no,hotkeys=nolocation=no');return false;" style="font-size:10px;">
				<span class="diff_label">Fr&uuml;hestes Ende:</span>
			</a>
			<br>
			<?php echo date("G:i:s", $this->earliestEnd); ?>
		</div>

		<?php if ($this->day['diff']>0): ?>
			<div id="day_diff">
				<span class="diff_label">Differenz:</span><br>
				<span class="day_diff_hour"><?php echo gmdate("G", $this->day['diff']) ?></span>:<span class="day_diff_minute"><?php echo gmdate("i", $this->day['diff']) ?></span>:<span class="day_diff_seconds"><?php echo gmdate("s", $this->day['diff']) ?></span>
			</div>
		<?php else:?>
			<div id="day_diff" class="negative">
				<span class="diff_label">Differenz heute:</span><br>
				<span class="day_diff_minus">-</span><span class="day_diff_hour"><?php echo gmdate("G", $this->day['diff']*-1) ?></span>:<span class="day_diff_minute"><?php echo gmdate("i", $this->day['diff']*-1) ?></span>:<span class="day_diff_seconds"><?php echo gmdate("s", $this->day['diff']*-1) ?></span>
			</div>
		<?php endif; ?>
	<?php endif; ?>

	<?php if ($this->data['months'][$this->curmonth]>0): ?>
		<div id="month_diff">
			<span class="diff_label"><?php echo formatmonth($this->curmonth) ?>:</span><br>
			<span class="month_diff_hour"><?php echo gmdate("G", $this->data['months'][$this->curmonth]) ?></span>:<span class="month_diff_minute"><?php echo gmdate("i", $this->data['months'][$this->curmonth]) ?></span>:<span class="month_diff_seconds"><?php echo gmdate("s", $this->data['months'][$this->curmonth]) ?></span>
		</div>
	<?php else:?>
		<div id="month_diff" class="negative">
			<span class="diff_label"><?php echo formatmonth($this->curmonth) ?>:</span><br>
			<span class="month_diff_minus">-</span><span class="month_diff_hour"><?php echo gmdate("G", $this->data['months'][$this->curmonth]*-1) ?></span>:<span class="month_diff_minute"><?php echo gmdate("i", $this->data['months'][$this->curmonth]*-1) ?></span>:<span class="month_diff_seconds"><?php echo gmdate("s", $this->data['months'][$this->curmonth]*-1) ?></span>
		</div>
	<?php endif; ?>

	<div style="clear:left"></div>

	<div class="day_subdata">
		<span class="diff_label">Urlaubstage <?php echo substr($this->curmonth, 0, 4); ?>:</span>
		<?php echo $this->subjectSum['vacation']; ?>
	</div>

	<div class="day_subdata">
		<span class="diff_label">Krankheitstage <?php echo substr($this->curmonth, 0, 4); ?>:</span>
		<?php echo $this->subjectSum['illness']; ?>
	</div>

	<div class="day_subdata">
	</div>

	<div class="day_subdata" id="action_field">
		<a href="calendar.php?y=<?php echo substr($this->curmonth, 0, 4) ?>" class="editorLink" rel="{handler:'iframe'}">Jahreskalender anzeigen</a> |
		<a href="download.php?h=<?php echo $this->hash ?>">Daemon downloaden</a> |
		<a href="index.php">Ausloggen</a>
	</div>
</div>

<div style="overflow:hidden" id="content_wrapper">
	<div class="leftColumn">
	<table>
		<thead>
			<tr>
				<th>Datum</th>
				<th>Anwesenheit</th>
				<th>Länge</th>
				<th>Pause</th>
				<th>Diff.</th>
				<th>Gesamt</th>
			</tr>
		</thead>
		<tbody>
		<?php
		$curmonth = substr($this->curmonth, 4, 2);
		$curyear = substr($this->curmonth, 0, 4);
		$daysInMonth = date('t',mktime(12,0,0, $curmonth,1,$curyear));
		for($i=1; $i <= $daysInMonth; $i++) :
			$daytimestamp = mktime(0,0,0,$curmonth, $i, $curyear);
			$dayOfWeek = date("N", $daytimestamp);
			if($dayOfWeek >= 6 || $daytimestamp > time()) continue;
			$curday = sprintf('%s-%02s-%02d', $curyear, $curmonth, $i);
			$cday = $this->data['days'][$curday];
		?>
		<tr class="<?php echo ($alt=!$alt ? 'alt' : '') ?>">
		<?php if(isset($cday)) : ?>
			<td>
				<a href="correct.php?date=<?php echo $curday ?>" class="correctionLink">
					<strong><?php echo date("d.m.Y", $daytimestamp); ?></strong>
				</a>
			</td>
			<td><?php echo date("G:i",$cday['startstamp'])?> - <?php echo date("G:i",$cday['endstamp'])?></td>
			<td><?php echo gmdate("G:i",$cday['worktime']) ?></td>
			<td><?php echo gmdate("G:i",$cday['pause']) ?></td>
			<td>
				<?php if ($cday['diff']>=0): ?>
				+<?php echo gmdate("G:i",$cday['diff']) ?>
				<?php else: ?>
				<span class="negative_value">-<?php echo gmdate("G:i",$cday['diff']*-1) ?></span>
				<?php endif; ?>
			</td>
			<td>
			<?php if ($cday['monthdiff']>=0): ?>
				+<?php echo gmdate("G:i",$cday['monthdiff']) ?>
			<?php else: ?>
				<span class="negative_value">-<?php echo gmdate("G:i",$cday['monthdiff']*-1) ?></span>
			<?php endif; ?>
			</td>
		<?php elseif(isset($this->holidays[$daytimestamp])) : ?>
			<td  class="holidays">
					<strong><?php echo date("d.m.Y", $daytimestamp); ?></strong>
			</td>
			<td colspan="5" class="holidays">
				<?php echo $this->holidays[$daytimestamp]; ?>
			</td>
		<?php elseif(isset($this->subjects[$curday])) : ?>
			<td class="specialday">
				<strong><?php echo date("d.m.Y", $daytimestamp); ?></strong>
			</td>
			<td class="specialday" colspan="5">
				<input type="hidden" name="unavail_date" value="<?php echo $curday ?>">
				<?php
				$subject = $this->subjects[$curday]['subject'];
				if($subject == "vacation") {
					echo "Urlaub";
				} elseif($subject == "illness") {
					echo "Krank";
				}
				?>
				<a href="javascript:;" class="unavail_remove">Eintrag entfernen</a>
			</td>

		<?php else: ?>
			<td>
				<strong><?php echo date("d.m.Y", $daytimestamp); ?></strong>
			</td>
			<td colspan="5">
				<input type="hidden" name="unavail_date" value="<?php echo $curday ?>">
				Bitte wählen:
				<span class="unavail unavail_illness">Krank</span>
				-
				<span class="unavail unavail_vacation">Urlaub</span>
			</td>
		<?php endif; ?>
		</tr>
		<?php endfor; ?>
		</tbody>
	</table>
	</div>

	<div class="rightColumn">
		<img src="<?php echo $this->presenceGraphUrl; ?>">
		<br>
		<img src="<?php echo $this->differenceGraphUrl; ?>">
		<dl>
			<dt>
				Hash:
			</dt>
			<dd>
				<?php if ($this->isWritable): ?>
					<a href="editor.php?m=<?php echo $this->curmonth ?>" class="editorLink" rel="{handler:'iframe'}" style="color: #fff; text-decoration: none;"><?php echo $this->hash ?></a>
				<?php else: ?>
					<?php echo $this->hash ?>
				<?php endif; ?>
			</dd>
			<dt>
				Benachrichtigungen
			</dt>
			<dd id="dd_notifications">
				<input type="checkbox" id="notificationEnabled" <?php if(isset($this->notifications['enabled']) && $this->notifications['enabled'] === true) echo "checked='checked'" ?>>
				Ich möchte

        <span id="notificationWhen" class="notificationSetting"><?php echo $this->notificationsMapping['when'][$this->notifications['when']]; ?></span>
				vor dem
				<span id="notificationWhat" class="notificationSetting"><?php echo $this->notificationsMapping['what'][$this->notifications['what']]; ?></span>
				Feierabend per
				<span id="notificationHow" class="notificationSetting"><?php echo $this->notificationsMapping['how'][$this->notifications['how']]; ?></span>
				informiert werden.
			</dd>
			<dt>
				Auto-Backup
			</dt>
			<dd>
				<a href="backup.php" class="iframeLink" rel="{handler:'iframe'}" style="color: #fff;">
				<?php
					$backupCount = 0;
					$backupsActive = array();
					if(isset($this->backups)) {
						foreach($this->backups as $backupName => $backup) {
							if($backup === true) {
								$backupCount++;
								$backupsActive[] = ucfirst($backupName);
							}
						}
					}
					if($backupCount > 0) {
						echo join(", ", $backupsActive);
					} else {
						echo "deaktiviert";
					}
				?>
				</a>
			</dd>
		</dl>
	</div>
<?php endif;?>
</div>
<div>
</div>
<script type="text/javascript">
<!--
var day_diff = <?php echo isset($this->normalEnd) ? $this->normalEnd : 0; ?>;
var earliest_diff = <?php echo isset($this->earliestEnd) ? $this->earliestEnd : 0; ?>;
var laststateIn = "<?php echo $this->day['laststateIn']?>";
var hash = "<?php echo $this->hash ?>";
-->
</script>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/mootools/1.4/mootools-yui-compressed.js"></script>
<script type="text/javascript" src="static/js/mootools-1.4.0.1-more.js"></script>
<script type="text/javascript" src="static/js/SqueezeBox/SqueezeBox.js"></script>
<script type="text/javascript" src="static/js/TimeSlider.js"></script>
<script type="text/javascript" src="static/js/show.js"></script>

<div id="options_notificationWhen" class="notificationSettingBox hidden">
	<ul>
		<?php foreach($this->notificationsMapping['when'] as $key => $value) : ?>
		<li class="notificationOption"><input type="hidden" name="when" value="<?php echo $key; ?>"><?php echo $value; ?></li>
		<?php endforeach; ?>
	</ul>
</div>

<div id="options_notificationWhat" class="notificationSettingBox hidden">
	<ul>
		<?php foreach($this->notificationsMapping['what'] as $key => $value) : ?>
		<li class="notificationOption"><input type="hidden" name="what" value="<?php echo $key; ?>"><?php echo $value; ?></li>
		<?php endforeach; ?>
	</ul>
</div>

<div id="options_notificationHow" class="notificationSettingBox hidden">
	<ul>
		<?php foreach($this->notificationsMapping['how'] as $key => $value) : ?>
		<li class="notificationOption"><input type="hidden" name="how" value="<?php echo $key; ?>"><?php echo $value; ?></li>
		<?php endforeach; ?>
	</ul>
</div>

<div id="options_notificationHow_email" class="hidden">
	<p>Für diese Benachrichtigung ist die Angabe einer Mailadresse erforderlich</p>
	<p><input type="text" value="email"><button>Speichern</button></p>
</div>
