<?php echo $this->doctype() ?>
<html lang="de">
<head>
	<?php echo  $this->headMeta()  ?>
	<?php echo  $this->headTitle()  ?>
	<?php echo  $this->headLink()  ?>
	<link rel="shortcut icon" href="images/favicon.ico" />
	<link rel="icon" href="images/favicon.ico" type="image/ico" />
	<link rel="apple-touch-icon" href="images/favicon.png">
	<link rel="apple-touch-startup-image" href="images/startupimage.png">
</head>
<body>
	<?php echo $this->layout()->content ?>
</body>
</html>
